### PR TITLE
Fix autotools warnings

### PR DESCRIPTION
**Pull request by bdrung**
autoreconf complains (examples):

```
warning: 'INCLUDES' is the old name for 'AM_CPPFLAGS' (or '*_CPPFLAGS')
mlxconfig/Makefile.am:66: error: 'libmlxcfg.a' is not a standard libtool library name
```

Therefore replace INCLUDES by AM_CPPFLAGS and fix libtool libraries names. These patches depends on merge request https://github.com/Mellanox/mstflint/pull/318.

### CODE REVIEW

**Comment by kstntnm** [comment]
The patch is not relevant to the current mstflint source tree. I tried to make all the changes manually, but failed to build mstflint.

**Comment by bdrung** [comment]
The patch is still relevant for the current mstflint source tree. You can see many errors and warnings when running `autoreconf -if`.

I rebased my patches and updated them to the current code.

**Comment by tomer540** [comment]
Closed due to time limit, if still require addressing – please open a new request.

**Comment by bdrung** [comment]
@tomer540 Will you review and merge the change if I rebase this MR again or will it be a waste of time to rebase it again?

**Pull request closed without merging**
