### PR TITLE
Fix fallthrough and other build warnings

### PR DESCRIPTION
**Pull request by tzafrir-mellanox**
Fix (or at least note) some of the build warnings that are spewed by the build process.

### CODE REVIEW

**Comment by mataneli94** [comment]
master branch is for releases only, please develop on master_devel branch.
Open a PR that merges into master_devel.

**Comment by tzafrir-mellanox** [comment]
Done.

**Comment by DanGoldbergMellanox** [comment]
Hi Tzafrir,
In your PR you used __attribute__((fallthrough)) that is not supported by all compilers (was added in GCC 7.0 as C++17 support), please change it to a comment (for example: /* Fall through */).

**Comment by tzafrir-mellanox** [comment]
Thanks for the note. Fixed.

**Pull request merged**
